apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:

  mapUsers: |
    - userarn: arn:aws:iam::289836653043:user/github-cli
     username: github-cli
      groups:
        - system:masters
