apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: promise2022/django:latest
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo Done Deploying django; sleep 3600;done"]
          ports:
            - containerPort: 8000
              name: django-api


