apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      containers:
      - name: deployment
        image: django
        env: 
          - name: PORT
            value: "8181"
        ports:
        - containerPort: 8181

---

apiVersion: v1
kind: Service
metadata:
  name: deploy-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8181
  selector:
    app: deploy-deployment
