name: Deploy to production

on:
  push:
    branches: [ master ]

  
env:
  POSTGRES_USER: POSTGRES_USER
  POSTGRES_PASSWORD: POSTGRES_PASSWORD
  POSTGRES_DB: POSTGRES_DB
  POSTGRES_HOST: POSTGRES_HOST 
  POSTGRES_PORT: POSTGRES_PORT


jobs:

  build:
    
    name: Build image 
    runs-on: ubuntu-latest
    

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            promise2022/django:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}
